config/routes.rb
HackerNews::Application.routes.draw do
  resources :sessions, :users, :links, :votes, :comments

  get "sign up", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  root :to => 'links#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :as => :commentable
  belongs_to :commentable, polymorphic: true

  def route_to_comment
  	if self.commentable.is_a?(Link)
  	  self.commentable
    else
  	  self.commentable.route_to_comment
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, :presence => true, :url => true
  belongs_to :user
  has_many :votes
  has_many :comments, :as => :commentable

  def self.sort_by_votes
    sorted_votes = Link.all.sort_by  { |link| link.votes.count }
    sorted_votes.reverse
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  has_many :votes
  has_many :comments
  
  validates_uniqueness_of :email

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  
  validates_uniqueness_of :user_id, scope: :link_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Your comment has been saved."
      redirect_to @comment.route_to_comment
    else
      
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Your comment has been removed."
  end

private

  def comment_params
    params.require(:comment).permit(:text, :commentable_type, :commentable_id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authorize, only: [:new, :create, :destroy]
 
  def index
    @links = Link.all
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(links_params)
    if @link.save
      flash[:notice] = "Your link has been saved."
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:notice] = "Your link has been removed."
    redirect_to root_path
  end

  def show
    @link = Link.find(params[:id])
  end

private

  def links_params
    params.require(:link).permit(:description, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user= User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged In"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

    def destroy
      session[:user_id] = nil
      redirect_to root_url, notice: "Logged out"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = Users.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to links_path, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end

private

  def users_params
    params.require(:user).permit(:name, :email, :user_name, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  def index
    @votes = Votes.all
  end

  def create
    @vote = current_user.votes.new(voter_params)
    if @vote.save
      redirect_to links_path, notice: "Thanks for voting!"
    else
      redirect_to links_path, notice: "Sorry, you can only vote on a link once."  
    end
  end


private

  def voter_params
    params.require(:vote).permit(:link_id)
  end

end 
 

app/controllers/voting_controller.rb
class VotesController < ApplicationController
  
  def index
    @votes = Votes.all
  end

  def create
    @vote = Vote.new(voter_params)
    if @vote.save
      redirect_to links_path, notice: "Thanks for voting!"
    end
  end

private

  def voter_params
    params.require(:vote).permit(:user_id, :link_id)
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/index.html.erb
<%= @

app/views/layouts/_comments.html.erb
<li class="list-group-item">
  <%= comment.text %>
  <%= form_for Comment.new do |f| %><br>
    <%= f.text_field :text %>
    <%= f.hidden_field :commentable_id, :value => comment.id %>
    <%= f.hidden_field :commentable_type, :value => comment.class %>
    <%= f.submit 'reply', :class => "btn btn-default" %>
  <% end %>
  <ul class="list-group">
    <% comment.comments.each do |reply| %>
      
      <%= render "/layouts/comments", :comment => reply %>
    <% end %>
  </ul>
</li>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h4>Please correct these problems:</h4>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Haxie News</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<nav class="navbar navbar-default" id="top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
<!--     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button> -->
    <a class="navbar-brand" id="title" href="/">Haxie News</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <% if current_user %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Log Out", logout_path %></li>
    </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log In", login_path %></li>
      </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign Up", new_user_path %></li>
    </ul>
    <% end %>
  </div><!-- /.navbar-collapse -->
</nav>
<body>

 <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>   
<%= yield %>
</body>
</html>

app/views/links/index.html.erb
<% if current_user %>
<p style="float:right; padding-right: 10px;"> Logged in as: <%= current_user.name %> </p>
<% end %>
<div class="container" id="content">
  <% if current_user %>
  <button class="btn btn-default btn-xs" style="float:right"><%= link_to "New Link", new_link_path %></button><br><br>
  <% end %>
<table >
  <thead> 
    <tr>
    </tr>
  </thead>
  <tbody class="stories">
    <% @links.sort_by_votes.each do |link| %>
          <%= form_for link.votes.new do |f| %>
                   <%= f.hidden_field :link_id %>
                   <% if current_user %>
                   <%= f.submit  '▲' %>
                   <% end %>
                   <% end %>
          <%= "#{link.votes.count} votes " %>
          <%= link_to link.description, link.url %>
          <small><%= "(#{link.url})" %></small>
          <span class="date"><%= link.created_at.to_time.strftime("%b %-d, %Y @ %-I:%M%P") %></span>
          <br>
          <% if current_user %>
          <button class="btn btn-default btn-xs">
            <%= link_to "Delete", link, :method => :delete, :data => { :confirm  => "are you sure about that?" } %>
          </button> 
          <button class="btn btn-default btn-xs">
            <%= link_to "Comment", link_path(link)%>
          </button><hr/>
          <% end %>
      <% end %>
</tbody>

</div>

app/views/links/new.html.erb
<div class="container" id="content">

<% if @link.errors.any? %>
  <h3>Please correct these problems:</h3>
    <ul>
      <% @link.errors.full_messages.each do |messages| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>


<%= form_for @link do |f| %>
  <%= f.label :description %><br>
  <%= f.text_field :description %> <br/>
  <%= f.label :url %> <br/>
  <%= f.text_field :url %><br><br>
  <%= f.submit %>
<% end %>
</div>

app/views/links/show.html.erb
<div class="jumbotron" style="font-size: 3em;">
<button class="btn btn-default btn-xs" style="float:right"><%= link_to "Back to Links", links_path %></button>
  <a href= <%= "'" + @link.url + "'"%> > <%= @link.description %></a><br>
</div>
<h6 id="content">
  <%= @link.url.gsub(/(http:\/\/ *)()/, "") %>
</h6>
<div class="container" id="content">

<p>
  <%= form_for Comment.new do |f| %>
    <%= f.text_field :text %>
    <%= f.hidden_field :commentable_id, :value => @link.id %>
    <%= f.hidden_field :commentable_type, :value => @link.class %>
    <%= f.submit  'add comment', :class => "btn btn-default" %>
  <% end %>    
</p>
<br>
<ul>
  <% @link.comments.each do |comment| %>
    <%= render "layouts/comments", :comment => comment %>
  <% end %>
</ul>
</div>

app/views/users/new.html.erb
<div class="container" id="content">

<% if @user.errors.any? %>
  <h3>Please correct these problems:</h3>
    <ul>
      <% @user.errors.full_messages.each do |messages| %>
        <li><%= messages %></li>
      <% end %>
    </ul>
<% end %>
<%= form_for @user do |f| %>
  <table>
    <tbody>
      <tr><td><%= f.label :name %></tr></td>
      <tr><td><%= f.text_field :name %></tr></td>
      <tr><td><%= f.label :email %></tr></td>
      <tr><td><%= f.text_field :email %></tr></td>
      <tr><td><%= f.label :user_name %></tr></td>
      <tr><td><%= f.text_field :user_name %></tr></td>
      <tr><td><%= f.label :password %></tr></td>
      <tr><td><%= f.password_field :password %></tr></td>
      <tr><td><%= f.label :password_confirmation %></tr></td>
      <tr><td><%= f.password_field :password_confirmation %></tr></td>
      <tr><td></tr></td>  
    </tbody>
  </table>
<%= f.submit 'sign up' %>
<% end %>
</div>